# Generated by Django 3.0.6 on 2020-05-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200517_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='extras',
        ),
        migrations.AddField(
            model_name='item',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.Extra'),
        ),
    ]
